#
#  docker run --name mypostgres \
#  -e POSTGRES_USER=root \
#  -e POSTGRES_PASSWORD=password \
#  -e POSTGRES_DB=mydatabase \
#  -p 5432:5432 \
#  -d postgres
#

# DATABASE CONFIGURATION
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE_NAME: mydatabase
POSTGRES_USERNAME: postgres
POSTGRES_PASSWORD: password

# EMAIL CONFIGURATION
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <your email address>
EMAIL_PASSWORD: <your app password>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}/auth/register/activate?token=

# SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

# DEBUGGING
logging:
  level:
    io.igorcossta.*: debug
spring:
  thymeleaf:
    cache: false