spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  # DATABASE CONFIG
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA CONFIG
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true
  # EMAIL CONFIG
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    verify-host: ${VERIFY_EMAIL_HOST}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
# SERVER CONFIG
server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
    path: /error

# APIs config
api:
  calories: <KEY>
